[build] # default master branch
  publish = "_site/"
  command = "ELEVENTY_ENV=production eleventy"
  environment = { ELEVENTY_ENV = 'production' } # to enable Eleventy to know the environment

[context.preview] # 'preview' is the branch name
  publish = "_site/"
  command = "ELEVENTY_ENV=preview eleventy"
  environment = { ELEVENTY_ENV = 'production' } # to enable Eleventy to know the environment

# https://github.com/netlify-labs/netlify-plugin-sitemap
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "_site/"
  changeFreq = "monthly"
  priority = 0.5
  trailingSlash = true
  exclude = [
    # By file Path
    '**/**/404/index.html'
  ]
