name: Eleventy Build and Deploy
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          args: --input ./src/
          install_dependencies: true

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_CONNECTION }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: ./public_html/
          state-name: ../.ftp-deploy-sync-state.json
          log-level: verbose
          dry-run: false
